### ISSUE TITLE
pyqt is required for processing time only?

### ISSUE THREAD

**Issue by lixxu** [Semi-ATE/STDF#43]
### Tasks/Steps/Elements
Why pyqt is required for processing time only? There're many packages for processing datetime, e.g. `python-dateutil`.
pyqt is a big package.

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by nerohmot** [comment]
@lixxu 🤣 valid question !

# The answer is as follows : 
Parsing STDF files is just the first step in the work one wants to do. Afterwards one wants to : 
- save the data (probably in a pandas data frame and likely in an HDF5 container) → that's what the [metis](https://github.com/Semi-ATE/Metis) project is all about.
- analyze the data with some tools that generate nice plots, and here, the chance Qt is used is relatively high. Actually the tools we plan we are planning *WILL* use Qt in the background as they will be implemented as plug-ins to spyder, and spyder uses Qt 😋

So the environment one uses should have Qt in any case for later stages, so the reasoning is to use it in the STDF parser to convert the date/times with Qt in mind (read that sub-subsequent tools using Qt can handle the format).

Now, we could detect if Qt is available, if so the STDF library uses Qt for the time/date transformations and if not, it use something from the python standard library (probably the datetime module) ... sounds not too crazy and that can be done ! 

(care to contribute ? 😉) 

# Good to know background :

You might have noticed that the [Qt on Anaconda](https://anaconda.org/anaconda/qt) is very old, the [Qt on conda-forge](https://anaconda.org/conda-forge/qt) is a bit younger, but still outdated and semi-broken (will not go into that one here). The Qt on PyPi is up-to-date, as it is maintained by [The Qt Company](https://www.qt.io/) ...

Problem now is that if you do a lot of development (read: different environments are needed), PyPi (read: using `pip`) is not an option because `pip` does EXACTLY what it is asked to do and literally nothing more! So much so that the installation of the dependencies of one package can <ins>destroy dependencies of other (pre-installed) packages</ins> 😭 !!! (I tell you, you are chasing your tail if something like that happens!)

That is the background behind the headaches of the [Spyder](https://www.spyder-ide.org/) developers that they try to mitigate in [this video](https://www.youtube.com/watch?v=Ul79ihg41Rs&t=80s)... 

Anyway long time ago [Travis Oliphant](https://www.linkedin.com/in/teoliphant/) dreamed up the `conda` project, initially implemented by [Ilan Schnell](https://www.linkedin.com/in/ilan-schnell-8699ba5/) at the time they where still at [Anaconda Inc](https://www.anaconda.com/).

With `conda` you have an **installer** and and **environment manager** <ins>rolled into one</ins>. And this installer will always respect pre-installed dependencies. 😍

Now `conda` will find the available packages in [Anaconda.org](https://anaconda.org/), specifically in the `main` and `free` channels. Although they have a lot, some packages are paying 😕... which to me is kind of mind boggling because there is a thingy called [conda-forge](https://conda-forge.org/) that has an order of magnitude (>17K) more conda packages (each one potentially for multiple operating systems, multiple processors and a whole shitload of versions) ...

One could install `conda` from `Anaconda Inc`, however than you only have the anaconda channels ... indeed with some knowledge you can add channels, remove others and get it to work with the conda-forge channel, but for the average user this is too much hassle!  That's whay we made the [maxiconda](https://www.maxiconda.org/) project. It is an installer for conda that is based **SOLELY** on the `conda-forge` channel, and it exists for windows, Linux (Intel & ARM) and macOS(Intel & ARM) 😎

Result: No more potential problems with Anaconda's "terms of use", and way more FREE packages at your fingertips !

It is thus not surprising that we are pushing the conda-forge guys to modernize Qt (and at the same time add aarch64 support ... I noticed your server is an RPi ...). As Qt is so humongous we agreed with the cond-forge guys to split Qt in two parts : [qt-main](https://anaconda.org/conda-forge/qt-main) and [qt-webengine](https://anaconda.org/semi-ate/qt-webengine) where as they are "held together" with the rather small `pyqt` package which actually is just the python front-end to Qt libraries.

- qt-main is already on [conda-forge channel](https://anaconda.org/conda-forge/qt-main)
- qt-webengine is not on conda-forge yet, the review is in progress, but we have the package on the [Semi-ATE channel](https://anaconda.org/semi-ate/qt-webengine).
- the conda recipes for pyqt are being made as we speak, probably by the end of CW8/22 they will be available on the Semi-ATE channel, and some time later on conda-forge (whenever the conda-forge guys approved them)

Once we have the above 3 packages available (regardless the channel), we will be able to run the latest spyder on all OS-es and Processors ! (including the RPi!)

**Comment by lixxu** [comment]
thank you for declaration. My need is getting the parsed data from STDF file. Yes, the first step is enough for me now.
