### ISSUE TITLE
Follow up: SDR.py when convert to ATDF is missing SITE_NUM if SITE_NUM is empty, PRR missing P/F flag #46

### ISSUE THREAD

**Issue by jervinkhoo** [Semi-ATE/STDF#48]
hello, sorry there might be a miscommunication, i'm not sure if you fixed the right thing or not from issue #46, it seems PRR.py is fixed and not SDR.py I actually raised 2 items here... 

1. regarding missing SITE_NUM in SDR.py: 

the SITE_NUM issue I referred to was regarding SDR, where SITE_NUM did not reflect when the list is empty
![image](https://user-images.githubusercontent.com/8014400/174511987-9ccfaa45-d340-4b17-a6bd-f5b0b0688095.png)

in the screenshots showed earlier, you can see that when using Semi-ATE-STDF, a pipe is missing if SITE_NUM is an empty array.

regarding missing SITE_NUM in PRR, when using both stdf4_to_atdf2.pl (perl) and stdfatdf.exe (teradyne binaries) 
from the same STDF file that has 4 sites(0,1,2,3), 
![image](https://user-images.githubusercontent.com/8014400/174512824-148ce1d4-1a5c-425b-8534-41a69486d518.png)

i'm not sure if the following fix is accurate:
> When SITE_NUM is missing I will set it to 1

however from my own internal testing
for a blank SITE_NUM in PRR, using stdf4_to_atdf2.pl (perl) will make an empty SITE_NUM to have the value of 0 and stdfatdf.exe (teradyne binaries) will make an empty SITE_NUM to have the value of 255.
perhaps reverting it to leaving it blank (NULL) after conversion from blank (NULL) is the most accurate?

attached here are the converted ATDFs in question, with *.atdf is converted using stdfatdf.exe (teradyne binaries)  and *.txt is converted using stdf4_to_atdf2.pl (perl) , and the original STDF as well
[stdfatdf.zip](https://github.com/Semi-ATE/STDF/files/8937010/stdfatdf.zip)

2. regarding the F flags in PRR: 

in other converters I used, including stdf4_to_atdf2.pl (perl), stdfatdf.exe (teradyne binaries) and pystdf (python), an F flag is raised even if is invalid. Perhaps you can fact check this claim of mine? you can use my attached files to test.
[stdfatdf.zip](https://github.com/Semi-ATE/STDF/files/8937010/stdfatdf.zip)

**Comment by seimit** [comment]
Hello Jervin,
It is my fault for misunderstanding : I saw in your previous issue the proposed patch in the STDR.py, but I miss that the issue is regarding SDR record. You could re-open the previous issue, but is not a problem to continue in this one. Note that once I merge the changes, the issue is closed automatically, but you can always open it again if my change does fix your problem.    
Regarding 1:
-> missing case when SITE_NUM is an array for the SDR record : I fully agree to add your proposal in the code.
-> I will revert the code for the empty SITE_NUM. It can cause additional problems if the SITE_NUM in the PIR record is not 1 and in PRR is 1.
Regarding 2:
I will double check why I can not reproduce the empty "Pass/Fail Code".

**Comment by seimit** [comment]
Using provided by you stdf file, I found the bug in the PRR to_atdf() function:
In line 105 I removed the old code for checking bits 3 and 4 :
"elif v != None and  v[4] == '1':"
Now the code will just set "F" if the previous condition fail (both bit 3 was set and bit 4 is 0)
Thanks again for reporting the issue!
If you have additional requests, let me know.
Kind Regards,
Seimit

**Comment by nerohmot** [comment]
@jervinkhoo 👍
